# Site settings
title: Patrick Rollings
email: no@email.com
description: > # this means to ignore newlines until "baseurl:"
  Just a little site to keep track of little projects and development of them.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prollings.github.io" # the base hostname & protocol for your site
twitter_username: teapotrick
github_username:  prollings

# Build settings
markdown: kramdown
